In [3]:
!uv pip list

Using Python 3.12.3 environment at: /home/manodeep/projects/NN/.venv
Package                   Version
------------------------- --------------
aiohappyeyeballs          2.6.1
aiohttp                   3.11.18
aiosignal                 1.3.2
anyio                     4.9.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
bash-kernel               0.10.0
beautifulsoup4            4.13.4
bleach                    6.2.0
certifi                   2025.4.26
cffi                      1.17.1
charset-normalizer        3.4.2
comm                      0.2.2
contourpy                 1.3.2
cycler                    0.12.1
datasets                  3.5.1
debugpy                   1.8.14
decorator                 5.2.1
defusedxml                0.7.1
dill                      0.3.8
executing                 2.2.0
fastjsons

In [1]:
with open("./data/input.txt" , "r" , encoding = "utf-8") as f:
    text = f.read()

In [2]:
text[:1000]

"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citizens, the patricians good.\nWhat authority surfeits on would relieve us: if they\nwould yield us but the superfluity, while it were\nwholesome, we might guess they relieved us humanely;\nbut they think we are too dear: the leanness that\nafflicts us, the object of our misery, is as an\ninventory to particularise their abundance; our\nsufferance is a gain to them Let us revenge this with\nour pikes, ere we become rakes: for the gods know I\nspeak this in hunger 

In [3]:
len(text)

1115394

In [7]:
chars = sorted(list(set(text)))

In [11]:
vocab_size = len(chars)
vocab_size

65

In [10]:
print(" ".join(chars))


   ! $ & ' , - . 3 : ; ? A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z


In [12]:
stoi = {ch : i for i , ch in enumerate(chars)}
itos = {i : ch for i , ch in enumerate(chars)}

In [14]:
stoi , itos

({'\n': 0,
  ' ': 1,
  '!': 2,
  '$': 3,
  '&': 4,
  "'": 5,
  ',': 6,
  '-': 7,
  '.': 8,
  '3': 9,
  ':': 10,
  ';': 11,
  '?': 12,
  'A': 13,
  'B': 14,
  'C': 15,
  'D': 16,
  'E': 17,
  'F': 18,
  'G': 19,
  'H': 20,
  'I': 21,
  'J': 22,
  'K': 23,
  'L': 24,
  'M': 25,
  'N': 26,
  'O': 27,
  'P': 28,
  'Q': 29,
  'R': 30,
  'S': 31,
  'T': 32,
  'U': 33,
  'V': 34,
  'W': 35,
  'X': 36,
  'Y': 37,
  'Z': 38,
  'a': 39,
  'b': 40,
  'c': 41,
  'd': 42,
  'e': 43,
  'f': 44,
  'g': 45,
  'h': 46,
  'i': 47,
  'j': 48,
  'k': 49,
  'l': 50,
  'm': 51,
  'n': 52,
  'o': 53,
  'p': 54,
  'q': 55,
  'r': 56,
  's': 57,
  't': 58,
  'u': 59,
  'v': 60,
  'w': 61,
  'x': 62,
  'y': 63,
  'z': 64},
 {0: '\n',
  1: ' ',
  2: '!',
  3: '$',
  4: '&',
  5: "'",
  6: ',',
  7: '-',
  8: '.',
  9: '3',
  10: ':',
  11: ';',
  12: '?',
  13: 'A',
  14: 'B',
  15: 'C',
  16: 'D',
  17: 'E',
  18: 'F',
  19: 'G',
  20: 'H',
  21: 'I',
  22: 'J',
  23: 'K',
  24: 'L',
  25: 'M',
  26: 'N',
  27:

In [15]:
encode = lambda s : [stoi[c] for c in s]
decode = lambda l : "".join([itos[i] for i in l])


In [16]:
encode("hi ")

[46, 47, 1]

In [17]:
decode([46 , 47 ,1 ])

'hi '

In [20]:
import torch
torch.__version__

'2.7.0+cu126'

In [22]:
dataset = torch.tensor(encode(text) , dtype = torch.long)

In [23]:
dataset.shape

torch.Size([1115394])

In [25]:
dataset[:100].dtype

torch.int64

In [29]:
n = int(0.9 * len(dataset))

train = dataset[:n]
val = dataset[n:]


train.shape , val.shape

(torch.Size([1003854]), torch.Size([111540]))

In [35]:
test = [int(i) for i in train[:100]]

In [36]:
decode(test)

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'

In [41]:
block_size = 8

In [42]:
x = train[:block_size]
y = train[1 : block_size + 1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]

    print(f"for context : {context} target : {target}")

for context : tensor([18]) target : 47
for context : tensor([18, 47]) target : 56
for context : tensor([18, 47, 56]) target : 57
for context : tensor([18, 47, 56, 57]) target : 58
for context : tensor([18, 47, 56, 57, 58]) target : 1
for context : tensor([18, 47, 56, 57, 58,  1]) target : 15
for context : tensor([18, 47, 56, 57, 58,  1, 15]) target : 47
for context : tensor([18, 47, 56, 57, 58,  1, 15, 47]) target : 58


In [156]:
# Dataloader
torch.manual_seed(42)

block_size = 8
batch_size = 4

def get_batch(split : str):
    data = train if split == 'train' else  val  


    idx = torch.randint(len(data) - block_size , (batch_size , ))

    
    x = torch.stack( [data[i : i + block_size] for i in idx] )
    y = torch.stack( [data[i + 1 : i + block_size +1 ] for i in idx] )
    # print(idx)
    return x , y



xb , yb = get_batch("train")

"input",xb,"target",yb


('input',
 tensor([[57,  1, 46, 47, 57,  1, 50, 53],
         [ 1, 58, 46, 43, 56, 43,  1, 41],
         [17, 26, 15, 17, 10,  0, 32, 53],
         [57, 58,  6,  1, 61, 47, 58, 46]]),
 'target',
 tensor([[ 1, 46, 47, 57,  1, 50, 53, 60],
         [58, 46, 43, 56, 43,  1, 41, 39],
         [26, 15, 17, 10,  0, 32, 53,  1],
         [58,  6,  1, 61, 47, 58, 46,  0]]))

In [157]:
## bigram language model

import torch
import torch.nn as nn
from torch.nn import functional as F



In [158]:
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        self.token_embedding_table = nn.Embedding(vocab_size , vocab_size)


    def forward(self, idx , targets = None):
        logits = self.token_embedding_table(idx) #(B,T,C)

        
        if targets is None:
            loss =  None

        else:
            
            B , T , C = logits.shape
    
            # print(f"B : {B} | T : {T} | C : {C}")
    
            logits  = logits.view(B*T , C)
            # print(f"logits shape : {logits.shape}")

            targets = targets.view(B*T)
            # print(f"targets shape : {targets.shape}")
    
            
            loss = F.cross_entropy(logits , targets)

        
        return logits , loss

    def generate(self , idx , max_new_tokens):

        for _ in range(max_new_tokens):

            logits , loss = self(idx)

            logits = logits[ : , -1 ,:] # (B , C)
        
            probs = F.softmax(logits , dim = 1)

            idx_next = torch.multinomial(probs , num_samples = 1) # (B , 1)

            idx = torch.cat((idx , idx_next) , dim = 1) # (B , T +1)


        # idx = self.decode(idx)
        return idx

    def decode(self , logits):

        return [decode(i)for i in logits.tolist()]  

n = BigramLanguageModel(vocab_size)

In [159]:
logits , loss = n(xb , yb)

In [160]:
logits.shape

torch.Size([32, 65])

In [161]:
loss

tensor(4.7241, grad_fn=<NllLossBackward0>)

In [162]:
logits = n.generate(xb , max_new_tokens = 100)

In [163]:
logits.shape

torch.Size([4, 108])

In [165]:
optimizer = torch.optim.AdamW(n.parameters() , lr = 1e-3)

In [166]:
n.parameters()

<generator object Module.parameters at 0x7beb0ca36260>

In [172]:
from tqdm import tqdm


batch_size = 32



for step in tqdm(range(10000)):
    xb , yb = get_batch('train')

    logits , loss = n(xb , yb)

    optimizer.zero_grad(set_to_none = True)

    loss.backward()

    optimizer.step()

    if step % 1000 == 0 :
        print(f"for epoch : {step} | loss : {loss}")

    
    


  0%|▏                                                         | 32/10000 [00:00<00:32, 310.56it/s]

for epoch : 0 | loss : 3.0237884521484375


 11%|██████▏                                                 | 1103/10000 [00:01<00:11, 768.11it/s]

for epoch : 1000 | loss : 2.7155497074127197


 21%|███████████▊                                            | 2110/10000 [00:02<00:11, 702.68it/s]

for epoch : 2000 | loss : 2.549657106399536


 31%|█████████████████▎                                      | 3083/10000 [00:04<00:09, 736.23it/s]

for epoch : 3000 | loss : 2.540620803833008


 41%|███████████████████████▏                                | 4135/10000 [00:05<00:08, 725.41it/s]

for epoch : 4000 | loss : 2.5854618549346924


 51%|████████████████████████████▍                           | 5089/10000 [00:07<00:07, 671.58it/s]

for epoch : 5000 | loss : 2.512922763824463


 61%|██████████████████████████████████▎                     | 6128/10000 [00:08<00:05, 667.15it/s]

for epoch : 6000 | loss : 2.607551336288452


 71%|███████████████████████████████████████▊                | 7114/10000 [00:10<00:04, 596.83it/s]

for epoch : 7000 | loss : 2.5376503467559814


 81%|█████████████████████████████████████████████▏          | 8076/10000 [00:11<00:03, 608.58it/s]

for epoch : 8000 | loss : 2.270321846008301


 91%|██████████████████████████████████████████████████▊     | 9067/10000 [00:13<00:01, 667.19it/s]

for epoch : 9000 | loss : 2.459124803543091


100%|███████████████████████████████████████████████████████| 10000/10000 [00:14<00:00, 672.25it/s]


In [177]:
n.decode(n.generate(idx = torch.zeros((1,1) , dtype = torch.long) , max_new_tokens = 500 ))

['\nPEOFr ongallouechodwen y br desoor aned meirstononyiffra:\nAng, VIN:\nMVais f stoiof s by ; h men what sar, e lly peve l nst\nWeafry athisisckindary ordingalvengrallounlo alund ha nen:\nPl w,\nEERGolllditht, tiso he bu wndetitherea I fatre eteybo cuclitisie anghauref Ma hesot ot an wsho f out.\nAR:\n\nmby tot ck! erthere my, at the w!\nCENNBo, henerd. hed.\n\nFoulsthanooledingorethir tor o m ce KItr s dosange bl hich t houspim?\nO:\n\nou ystooundngit d, the e ferouthid t wags, tave ineathim heft wownemathon h']

In [187]:
T = 8

tril = torch.ones(T ,T )
tril = torch.tril(tril)


wei = torch.zeros(T , T)
wei = wei.masked_fill(tril == 0 , float('-inf'))
wei = F.softmax(wei , dim =-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [191]:
ran = torch.arange(T)
ran.shape

torch.Size([8])

In [196]:
head_size = 16 

In [211]:

B ,T , C = 4 , 8 , 32

x = torch.randn(B, T, C)

key = nn.Linear(C , head_size , bias  = False)
query = nn.Linear(C , head_size , bias  = False)
value = nn.Linear(C , head_size , bias  = False)

k = key(x)

q = query(x)

v = value(x)
k.shape , q.shape

(torch.Size([4, 8, 16]), torch.Size([4, 8, 16]))

In [218]:
wei = q @ k.transpose(-2 , -1) * head_size** -0.5

In [219]:
wei.shape

torch.Size([4, 8, 8])

In [214]:
tril = torch.ones(T ,T )
tril = torch.tril(tril)


wei = torch.zeros(T , T)
wei = wei.masked_fill(tril == 0 , float('-inf'))
wei = F.softmax(wei , dim =-1)

In [215]:
out = wei @ v

In [217]:
wei.shape

torch.Size([8, 8])